"""変更内容の説明

Revision ID: abffa78d850d
Revises: 75cadcbcfeb8
Create Date: 2025-09-24 04:20:49.068895

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "abffa78d850d"
down_revision: str | None = "75cadcbcfeb8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
